name: cart
description: "A new Flutter package project."
version: 0.0.0
homepage:
resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  component_library: ^0.0.0
  flutter_bloc: ^9.1.1
  api: ^0.0.1
  domain_models: ^0.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
