name: ai_integration
description: A starting point for Dart libraries or applications.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  http: ^1.4.0
  firebase_ai: ^2.0.0
  record: ^6.0.0
  functions: ^0.0.1


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
