name: domain_models
description: A starting point for Dart libraries or applications.
version: 0.0.0+dev
resolution: workspace

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
