name: emakit
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.0

workspace:
  - packages/domain_models
  - packages/dataconnect
  - packages/component_library
  - packages/functions

  - packages/features/filter
  - packages/features/cart
  - packages/features/checkout
  - packages/features/profile
  - packages/features/product_details
  - packages/features/order_details
  - packages/features/add_edit_product
  - packages/features/product_list
  - packages/features/manage_categories

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.1
  dataconnect: ^0.0.0
  domain_models: ^0.0.0
  component_library: ^0.0.0

  functions: ^0.0.1

  filter: ^0.0.0
  cart: ^0.0.0
  checkout: ^0.0.0
  profile: ^0.0.0
  product_details: ^0.0.0
  order_details: ^0.0.0
  add_edit_product: ^0.0.1
  product_list: ^0.0.0
  manage_categories: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
