name: emakit
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.0

workspace:
  - apps/salone_bazaar

  - packages/product_repository
  - packages/order_repository
  - packages/user_repository
  - packages/store_repository
  - packages/address_repository
  - packages/payment_repository

  - packages/domain_models
  - packages/dataconnect
  - packages/component_library

  - packages/features/cart
  - packages/features/checkout
  - packages/features/profile
  - packages/features/product_details
  - packages/features/order_details
  - packages/features/add_edit_product
  - packages/features/product_list
  - packages/features/sign_in
  - packages/features/order_list
  - packages/features/seller_onboarding
  - packages/features/seller_dashboard
  - packages/features/store_product_details
  - packages/features/store_product_list
  - packages/features/store_order_details
  - packages/features/store_order_list
  - packages/features/complete_profile
  - packages/features/home
  - packages/features/store_info
  - packages/features/store_discovery
  - packages/category_repository
  - packages/cart_repository
  - packages/features/product_search



environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
