name: emakit
description: "A new Flutter project."
publish_to: "none"
version: 0.0.0

workspace:
  - apps/salone_bazaar
  - apps/sl_baz_admin
  - apps/bazaar

  - packages/domain_models
  - packages/component_library

  - packages/repositories/product_repository
  - packages/repositories/order_repository
  - packages/repositories/user_repository
  - packages/repositories/store_repository
  - packages/repositories/address_repository
  - packages/repositories/payment_repository
  - packages/repositories/category_repository
  - packages/repositories/cart_repository

  - packages/features/cart
  - packages/features/checkout
  - packages/features/profile
  - packages/features/product_details
  - packages/features/order_details
  - packages/features/product_list
  - packages/features/sign_in
  - packages/features/order_list
  - packages/features/seller_onboarding
  - packages/features/seller_dashboard
  - packages/features/store_product_details
  - packages/features/store_product_list
  - packages/features/store_order_details
  - packages/features/store_order_list
  - packages/features/home
  - packages/features/store_info
  - packages/features/store_discovery
  - packages/features/product_search
  - packages/features/category_management
  - packages/features/product_add_image_search
  - packages/features/product_add_or_edit
  - packages/features/product_variation

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
