name: emakit
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.0+dev

workspace:
  - packages/domain_models
  - packages/backend
  - packages/component_library

  - packages/screens/home_screen

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  backend: ^0.0.0+dev
  domain_models: ^0.0.0+dev
  component_library: ^0.0.0+dev
  home_screen: ^0.0.0+dev
  firebase_core: ^3.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
