name: emakit
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.0

workspace:
  - packages/domain_models
  - packages/api
  - packages/component_library
  - packages/features/filter
  - packages/features/cart
  - packages/features/checkout
  - packages/features/profile
  - packages/features/product_details
  - packages/features/order_details
  - packages/features/add_edit_product
  - packages/features/product_list
  - packages/features/manage_categories
  - packages/features/sign_in
  - packages/features/order_list
  - packages/features/seller_onboarding
  - packages/features/seller_dashboard

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.1
  api: ^0.0.1
  domain_models: ^0.0.0
  component_library: ^0.0.0
  filter: ^0.0.0
  cart: ^0.0.0
  checkout: ^0.0.0
  profile: ^0.0.0
  product_details: ^0.0.0
  order_details: ^0.0.0
  add_edit_product: ^0.0.1
  product_list: ^0.0.0
  manage_categories: ^0.0.1
  sign_in: ^0.0.1
  seller_onboarding: ^0.0.1
  order_list: ^0.0.1
  seller_dashboard: ^0.0.1
  go_router: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
