name: dataconnect
description: A starting point for Dart libraries or applications.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  firebase_data_connect: ^0.2.0+2
  domain_models: ^0.0.0
  firebase_auth: ^6.0.2
  cloud_functions: ^6.0.1
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  uuid: ^4.5.1


dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
