name: dataconnect
description: A starting point for Dart libraries or applications.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  firebase_data_connect: ^0.1.5
  domain_models: ^0.0.0
  firebase_auth: ^5.6.2
  cloud_functions: ^5.6.1
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.10
  uuid: ^4.5.1


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
