name: store_product_details
description: "A new Flutter package project."
version: 0.0.1
homepage:
resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  component_library: ^0.0.0
  dataconnect: ^0.0.1
  domain_models: ^0.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
