name: user_repository
description: A starting point for Dart libraries or applications.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  google_sign_in: ^7.1.1
  firebase_auth: ^6.0.2
  domain_models: ^0.0.0
  supabase_flutter: ^2.10.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
