name: add_edit_product
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace


environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  image_picker: ^1.1.2
  component_library: ^0.0.0
  domain_models: ^0.0.0
  api: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
