name: backend
description: A starting point for Dart libraries or applications.
version: 0.0.0
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  firebase_data_connect: ^0.1.5
  cloud_functions: ^5.5.1
  domain_models: ^0.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
