name: order_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
resolution: workspace

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  domain_models: ^0.0.0
  supabase_flutter: ^2.10.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
