name: product_list
description: "A new Flutter package project."
version: 0.0.0
resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  component_library: ^0.0.0
  domain_models: ^0.0.0
  dataconnect: ^0.0.1


  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  infinite_scroll_pagination: ^5.1.0
  equatable: ^2.0.7
  category_repository: ^1.0.0
  product_repository: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
