name: seller_onboarding
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  component_library: ^0.0.0
  dataconnect: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0