name: profile
description: "A new Flutter package project."
version: 0.0.0
resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  component_library: ^0.0.0
  dataconnect: ^0.0.1
  flutter_bloc: ^9.1.1
  domain_models: ^0.0.0
  user_repository: ^0.0.1
  equatable: ^2.0.7
  store_repository: ^0.0.1
  bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
