name: functions
description: A starting point for Dart libraries or applications.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  cloud_functions: ^5.5.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
