name: payment_repository
description: A starting point for Dart libraries or applications.
version: 0.0.1
resolution: workspace

# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  supabase_flutter: ^2.10.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
