name: component_library
description: "A new Flutter package project."
version: 0.0.0
resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  badges: ^3.1.2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.0+1
  speech_to_text: ^7.0.0
  record: ^6.0.0
  http: ^1.4.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - "assets/images/google_icon.png"
    - "assets/images/become_a_seller.png"
    - "assets/images/custom_design.png"
    - "assets/images/sign-in-required.png"
